import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowRight,CheckCircle2,Clock3,Copy,LockKeyhole,RefreshCw,ShieldCheck,Smartphone,WalletCards}from'lucide-react';import'./styles.css';
const nets=[['BNB Smart Chain','BEP-20','BNB'],['TRON','TRC-20','TRX'],['Arbitrum','Arbitrum One','ETH'],['Bitcoin','BTC','BTC'],['Solana','SPL','SOL']];
const words=['orbit','canvas','river','silver','garden','pilot','candle','north','velvet','signal','maple','stone'];
function App(){const[s,setS]=useState('welcome');const[u,setU]=useState('500');const[n,setN]=useState(0);const[m,setM]=useState('UPI');const rate=107,inr=(Number(u)||0)*rate;const Header=()=> <header><div className="brand"><i>T</i><b>Trust<span>Pay</span></b></div><small>🛡 Secure</small></header>;
if(s==='welcome')return <main><Header/><section className="hero"><div className="orb"><WalletCards size={44}/></div><small className="eyebrow">PRIVATE • FAST • SIMPLE</small><h1>USDT to INR,<br/><em>made simple.</em></h1><p>Exchange USDT for Indian Rupees with a premium, secure experience.</p><div className="rate"><span>LIVE EXCHANGE RATE<strong>₹107 <small>/ 1 USDT</small></strong></span><b>✓ Fixed rate</b></div><button onClick={()=>setS('phrase')}>Get started <ArrowRight/></button><label className="trust"><LockKeyhole/> Your recovery phrase stays on your device</label></section><footer>TrustPay • Secure digital asset exchange</footer></main>;
if(s==='phrase')return <main><Header/><section className="card"><small className="eyebrow">STEP 1 OF 2</small><h2>Your recovery phrase</h2><p>These 12 words are your wallet recovery credential. <b>Never share them.</b></p><div className="phrase">{words.map((w,i)=><div key={w}><small>{i+1}</small>{w}</div>)}</div><div className="warning">🔐 Write these words down and keep them offline. TrustPay will never ask for your phrase.</div><button onClick={()=>setS('home')}>I saved my phrase <ArrowRight/></button></section></main>;
if(s==='deposit')return <main><Header/><section className="card"><button className="back" onClick={()=>setS('home')}>← Back</button><small className="eyebrow">DEPOSIT USDT</small><h2>Choose network</h2><p>Send at least <b>500 USDT</b> to your TrustPay deposit address.</p><div>{nets.map((x,i)=><button className={'network '+(n===i?'selected':'')} onClick={()=>setN(i)} key={x[0]}><i>{x[2]}</i><span><b>{x[0]}</b><small>{x[1]}</small></span>›</button>)}</div><div className="address"><small>DEPOSIT ADDRESS • {nets[n][0].toUpperCase()}</small><code>ADDRESS_NOT_CONFIGURED</code><button><Copy/></button><p>Admin wallet address must be configured before production use.</p></div><button onClick={()=>setS('orders')}>I've sent the USDT <ArrowRight/></button></section></main>;
if(s==='withdraw')return <main><Header/><section className="card"><button className="back" onClick={()=>setS('home')}>← Back</button><small className="eyebrow">WITHDRAW INR</small><h2>Where should we send it?</h2><div className="tabs">{['UPI','IMPS'].map(x=><button className={m===x?'active':''} onClick={()=>setM(x)}>{x}</button>)}</div><label>{m} details<input placeholder={m==='UPI'?'name@upi':'Account number / IFSC'}/></label><label>Amount<input value={'₹'+inr.toLocaleString('en-IN')} readOnly/></label><div className="summary"><span>Processing target</span><b><Clock3/> ~15 minutes</b></div><button onClick={()=>setS('orders')}>Request withdrawal <ArrowRight/></button></section></main>;
if(s==='orders')return <main><Header/><section className="card center"><div className="success"><CheckCircle2 size={40}/></div><small className="eyebrow">ORDER RECEIVED</small><h2>We’re on it.</h2><p>Your request is recorded. Processing is targeted for approximately 15 minutes, subject to network confirmation and verification.</p><div className="order"><span>ORDER</span><b>TP-20260910</b><span>STATUS</span><b className="pending">Processing</b></div><button onClick={()=>setS('home')}>Back to dashboard</button></section></main>;
return <main><Header/><section className="dashboard"><div className="greet"><span><small>TRUSTPAY WALLET</small><h2>Good to see you.</h2></span><i>S</i></div><div className="balance"><small>AVAILABLE BALANCE</small><strong>{Number(u).toLocaleString()} <small>USDT</small></strong><span>≈ ₹{inr.toLocaleString('en-IN')}</span></div><div className="converter"><label>YOU SEND<input value={u} onChange={e=>setU(e.target.value.replace(/[^0-9.]/g,''))}/><b>USDT</b></label><RefreshCw/><label>YOU RECEIVE<input value={'₹'+inr.toLocaleString('en-IN')} readOnly/><b>INR</b></label></div><small className="min">Minimum exchange amount: 500 USDT</small><div className="actions"><button onClick={()=>setS('deposit')}>Deposit USDT</button><button disabled={Number(u)<500} onClick={()=>setS('withdraw')}>Withdraw INR</button></div><div className="features"><span><ShieldCheck/> <b>Secure</b><small>Protected flow</small></span><span><Clock3/><b>~15 min</b><small>Processing target</small></span><span><Smartphone/><b>UPI / IMPS</b><small>Indian payouts</small></span></div></section><nav><button>Wallet</button><button onClick={()=>setS('orders')}>Orders</button><button>Profile</button></nav></main>}
createRoot(document.getElementById('root')!).render(<App/>);