import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QRCodeSVG } from 'qrcode.react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Copy, FileCheck2, KeyRound, LockKeyhole, LogOut, Menu, RefreshCw, ShieldCheck, Smartphone, Upload, UserRound, WalletCards, XCircle } from 'lucide-react';
import './styles.css';

type Screen = 'welcome'|'phrase'|'login'|'home'|'deposit'|'withdraw'|'orders'|'profile'|'admin';
type DepositStatus = 'pending'|'verified'|'rejected';
type Network = {name:string;standard:string;ticker:string;address:string};

const RATE = 107;
const MIN_USDT = 500;
const networks: Network[] = [
 {name:'BNB Smart Chain',standard:'BEP-20',ticker:'BNB',address:'0xdc114586391B39216c8CD17B3bdDb02dF3CC5F0A'},
 {name:'TRON',standard:'TRC-20',ticker:'TRX',address:'TMVhrv1qfySpPfsuUghb19TuZvjzXukD9K'},
 {name:'Arbitrum',standard:'Arbitrum One',ticker:'ETH',address:'0xdc114586391B39216c8CD17B3bdDb02dF3CC5F0A'},
 {name:'Bitcoin',standard:'BTC',ticker:'BTC',address:'bc1qxny7h6hpkuw47sgmqn228m46k2zmvhexpcns0h'},
 {name:'Solana',standard:'SPL',ticker:'SOL',address:'7rV7Bkz4sjxYDZmhCQPR6WpueXYnZYw35NUFkj6mfGde'}
];
const seedWords = ['orbit','canvas','river','silver','garden','pilot','candle','north','velvet','signal','maple','stone'];
const initialDeposits = [{id:'TP-D-001',network:'Solana',amount:500,hash:'Awaiting transaction hash',status:'pending' as DepositStatus}];

function App(){
 const [screen,setScreen]=useState<Screen>('welcome');
 const [network,setNetwork]=useState(0);
 const [amount,setAmount]=useState('500');
 const [method,setMethod]=useState<'UPI'|'IMPS'>('UPI');
 const [txHash,setTxHash]=useState('');
 const [depositAmount,setDepositAmount]=useState('500');
 const [phrase,setPhrase]=useState(seedWords);
 const [copied,setCopied]=useState(false);
 const [deposits,setDeposits]=useState(initialDeposits);
 const [adminWallets,setAdminWallets]=useState(networks);
 const [toast,setToast]=useState('');
 const [showMenu,setShowMenu]=useState(false);
 const inr=(Number(amount)||0)*RATE;
 const selected=adminWallets[network];
 const notify=(msg:string)=>{setToast(msg);window.setTimeout(()=>setToast(''),2200)};
 const copyAddress=async()=>{await navigator.clipboard?.writeText(selected.address);setCopied(true);notify('Address copied');window.setTimeout(()=>setCopied(false),1400)};
 const createOrder=()=>{if(Number(depositAmount)<MIN_USDT){notify('Minimum deposit is 500 USDT');return} if(!txHash.trim()){notify('Enter your transaction hash');return} const id='TP-'+Math.floor(100000+Math.random()*900000);setDeposits(d=>[{id,network:selected.name,amount:Number(depositAmount),hash:txHash.trim(),status:'pending'},...d]);setScreen('orders');notify('Deposit submitted for verification')};
 const generateNewPhrase=()=>{setPhrase([...seedWords].sort(()=>Math.random()-0.5));notify('New demo phrase generated')};
 const verify=(id:string,status:DepositStatus)=>{setDeposits(d=>d.map(x=>x.id===id?{...x,status}:x));notify(status==='verified'?'Deposit marked verified':'Deposit rejected')};
 const updateWallet=(idx:number,value:string)=>setAdminWallets(w=>w.map((x,i)=>i===idx?{...x,address:value}:x));
 const Header=({admin=false}:{admin?:boolean})=><header><button className="brand" onClick={()=>setScreen(admin?'admin':'home')}><span className="brandMark">T</span><b>Trust<span>Pay</span></b></button><div className="headRight"><span className="secure"><ShieldCheck size={14}/> Protected</span>{!admin&&<button className="iconBtn" onClick={()=>setShowMenu(!showMenu)}><Menu size={20}/></button>}</div>{showMenu&&!admin&&<div className="menu"><button onClick={()=>{setScreen('profile');setShowMenu(false)}}><UserRound/> Profile</button><button onClick={()=>{setScreen('admin');setShowMenu(false)}}><FileCheck2/> Admin</button></div>}</header>;
 const Back=()=> <button className="back" onClick={()=>setScreen('home')}><ArrowLeft size={16}/> Back</button>;
 if(screen==='welcome')return <main><Header/><section className="hero"><div className="orb"><WalletCards size={42}/></div><small className="eyebrow">PRIVATE • FAST • SIMPLE</small><h1>USDT to INR,<br/><em>made simple.</em></h1><p>Convert USDT to Indian Rupees through a clear, verification-first exchange flow.</p><div className="rate"><div><small>EXCHANGE RATE</small><strong>₹107 <span>/ 1 USDT</span></strong></div><b><Check size={14}/> Fixed</b></div><button onClick={()=>setScreen('phrase')}>Create wallet <ArrowRight/></button><button className="ghostBtn" onClick={()=>setScreen('login')}>Restore with recovery phrase</button><div className="trust"><LockKeyhole size={14}/> Recovery credentials stay on your device</div></section><footer>TrustPay • Digital asset exchange interface</footer></main>;
 if(screen==='phrase')return <main><Header/><section className="card"><small className="eyebrow">STEP 1 OF 2 • RECOVERY</small><h2>Your recovery phrase</h2><p>Use this 12-word credential to restore your TrustPay wallet. <b>Never share it with anyone.</b></p><div className="phrase">{phrase.map((w,i)=><div key={i}><small>{i+1}</small>{w}</div>)}</div><div className="warning"><KeyRound size={17}/><span>For production, generate this phrase with a cryptographically secure BIP-39 implementation and never send or store the phrase on a server.</span></div><div className="rowBtns"><button className="secondary" onClick={generateNewPhrase}><RefreshCw size={17}/> Regenerate</button><button onClick={()=>setScreen('home')}>I saved it <ArrowRight/></button></div></section></main>;
 if(screen==='login')return <main><Header/><section className="card"><Back/><small className="eyebrow">RESTORE WALLET</small><h2>Enter your 12 words</h2><p>The phrase is processed locally. It is not displayed back to you or intentionally stored by this UI.</p><textarea className="phraseInput" placeholder="word1 word2 word3 … word12" rows={5}/><button onClick={()=>{setScreen('home');notify('Wallet restored on this device')}}>Restore wallet <ArrowRight/></button><div className="secureBox"><ShieldCheck/> <span>Everyday access should use device PIN/biometric in the production Android build.</span></div></section></main>;
 if(screen==='deposit')return <main><Header/><section className="card"><Back/><small className="eyebrow">DEPOSIT USDT</small><h2>Send USDT</h2><p>Minimum exchange amount is <b>500 USDT</b>. Select the exact network you will use.</p><div className="networkList">{adminWallets.map((x,i)=><button className={'network '+(network===i?'selected':'')} key={x.name} onClick={()=>setNetwork(i)}><span className="coin">{x.ticker.slice(0,3)}</span><span className="networkText"><b>{x.name}</b><small>{x.standard}</small></span>{network===i?<Check size={18}/>:<ArrowRight size={16}/>}</button>)}</div><div className="depositPanel"><div className="qr"><QRCodeSVG value={selected.address} size={190} bgColor="#fff" fgColor="#090c12" level="H" includeMargin/></div><div className="addressLabel">{selected.name.toUpperCase()} • {selected.standard}</div><div className="addressRow"><code>{selected.address}</code><button className="copy" onClick={copyAddress}>{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><div className="danger"><span>!</span> Only send USDT on {selected.standard} to this address. Sending the wrong asset/network can result in permanent loss.</div></div><label className="field">AMOUNT SENT<input value={depositAmount} inputMode="decimal" onChange={e=>setDepositAmount(e.target.value.replace(/[^0-9.]/g,''))} placeholder="500"/><span>USDT</span></label><label className="field">TRANSACTION HASH<input value={txHash} onChange={e=>setTxHash(e.target.value.trim())} placeholder="Paste blockchain transaction hash"/></label><button onClick={createOrder}>Submit for verification <ArrowRight/></button><small className="hint">TrustPay credits deposits only after independent transaction verification.</small></section></main>;
 if(screen==='withdraw')return <main><Header/><section className="card"><Back/><small className="eyebrow">WITHDRAW INR</small><h2>Receive ₹{inr.toLocaleString('en-IN')}</h2><div className="tabs">{(['UPI','IMPS'] as const).map(x=><button key={x} className={method===x?'active':''} onClick={()=>setMethod(x)}>{x}</button>)}</div><label className="field">{method==='UPI'?'UPI ID':'BANK ACCOUNT NUMBER'}<input placeholder={method==='UPI'?'name@upi':'Account number'}/></label>{method==='IMPS'&&<label className="field">IFSC CODE<input placeholder="IFSC"/></label>}<div className="summary"><span>USDT amount</span><b>{Number(amount).toLocaleString()} USDT</b><span>Rate</span><b>₹{RATE} / USDT</b><span>Processing target</span><b><Clock3 size={15}/> ~15 minutes</b></div><button disabled={Number(amount)<MIN_USDT} onClick={()=>{setScreen('orders');notify('Withdrawal request queued for review')}}>Request withdrawal <ArrowRight/></button><small className="hint">Payouts require verified funds and secure backend authorization.</small></section></main>;
 if(screen==='orders')return <main><Header/><section className="card"><Back/><small className="eyebrow">ORDER CENTER</small><h2>Verification queue</h2><p>Deposits remain pending until the backend verifies the blockchain transaction and amount.</p>{deposits.map(d=><div className="orderCard" key={d.id}><div className="orderTop"><b>{d.id}</b><span className={'status '+d.status}>{d.status}</span></div><div className="orderGrid"><span>Network</span><b>{d.network}</b><span>Amount</span><b>{d.amount} USDT</b><span>Hash</span><code>{d.hash}</code></div></div>)}<button className="secondary" onClick={()=>setScreen('deposit')}>New deposit <ArrowRight/></button></section></main>;
 if(screen==='profile')return <main><Header/><section className="card"><Back/><small className="eyebrow">ACCOUNT & SECURITY</small><h2>TrustPay wallet</h2><div className="profileItem"><UserRound/><div><b>Wallet identity</b><small>Recovery phrase based</small></div></div><div className="profileItem"><ShieldCheck/><div><b>Device security</b><small>Use PIN / biometric for everyday access</small></div></div><div className="profileItem"><LogOut/><div><b>Session</b><small>Local demo session active</small></div></div><button className="dangerBtn" onClick={()=>setScreen('welcome')}>Lock wallet</button></section></main>;
 if(screen==='admin')return <main className="adminMain"><Header admin/><section className="card adminCard"><div className="adminTitle"><div><small className="eyebrow">ADMIN CONSOLE</small><h2>Operations</h2></div><span className="adminBadge">Protected area</span></div><div className="stats"><div><b>{deposits.filter(d=>d.status==='pending').length}</b><small>Pending deposits</small></div><div><b>{deposits.filter(d=>d.status==='verified').length}</b><small>Verified</small></div><div><b>₹{(deposits.reduce((a,d)=>a+d.amount,0)*RATE).toLocaleString('en-IN')}</b><small>Gross INR value</small></div></div><h3>Wallet addresses</h3><p className="hint">These are the addresses supplied for this build. In production, save them in a protected database and audit every change.</p>{adminWallets.map((w,i)=><div className="walletAdmin" key={w.name}><div className="walletHead"><b>{w.name}</b><small>{w.standard}</small></div><input value={w.address} onChange={e=>updateWallet(i,e.target.value)}/><div className="uploadRow"><label className="upload"><Upload size={15}/> Upload QR<input type="file" accept="image/*" onChange={e=>e.currentTarget.files?.[0]&&notify(`${w.name} QR selected`)} /></label><button className="secondary miniBtn" onClick={()=>notify('Wallet address saved to local demo state')}><Check size={15}/> Save</button></div></div>)}<h3>Deposit verification</h3>{deposits.map(d=><div className="verifyCard" key={d.id}><div><b>{d.id}</b><small>{d.network} • {d.amount} USDT</small><code>{d.hash}</code></div><div className="verifyBtns"><button disabled={d.status==='verified'} onClick={()=>verify(d.id,'verified')}><Check size={15}/> Verify</button><button className="dangerBtn" disabled={d.status==='rejected'} onClick={()=>verify(d.id,'rejected')}><XCircle size={15}/> Reject</button></div></div>)}<div className="adminNote"><LockKeyhole size={17}/> No private keys, recovery phrases, or payout credentials belong in this admin panel.</div></section></main>;
 return <main><Header/><section className="dashboard"><div className="greet"><div><small>TRUSTPAY WALLET</small><h2>Good to see you.</h2></div><button className="avatar" onClick={()=>setScreen('profile')}>T</button></div><div className="balance"><small>ESTIMATED BALANCE</small><strong>{Number(amount).toLocaleString()} <span>USDT</span></strong><div>≈ ₹{inr.toLocaleString('en-IN')}</div></div><div className="converter"><label>YOU SEND<input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))}/><b>USDT</b></label><RefreshCw size={18}/><label>YOU RECEIVE<input value={'₹'+inr.toLocaleString('en-IN')} readOnly/><b>INR</b></label></div><small className="min">Minimum exchange: 500 USDT</small><div className="actions"><button onClick={()=>setScreen('deposit')}>Deposit USDT</button><button className="secondary" disabled={Number(amount)<MIN_USDT} onClick={()=>setScreen('withdraw')}>Withdraw INR</button></div><div className="features"><span><ShieldCheck/><b>Verification first</b><small>On-chain review</small></span><span><Clock3/><b>~15 min</b><small>Processing target</small></span><span><Smartphone/><b>UPI / IMPS</b><small>INR payout rails</small></span></div><div className="quick"><button onClick={()=>setScreen('orders')}><FileCheck2/> Orders</button><button onClick={()=>setScreen('profile')}><UserRound/> Profile</button></div></section><nav><button className="active"><WalletCards/>Wallet</button><button onClick={()=>setScreen('orders')}><FileCheck2/>Orders</button><button onClick={()=>setScreen('profile')}><UserRound/>Profile</button></nav></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);